### ISSUE TITLE
User can purchase animal stock

### ISSUE THREAD

**Issue by stevebrownlee** [nashville-software-school/Trestlebridge-Farms#1]
**Given** a user has launched the program
**When** the user selects the option to purchase an animal
**Then** the user should be presented with a list of animals to purchase

**Given** user is viewing a list of animals
**When** the user selects an animal
**Then** the user should be presented with a list of facilities for that animal

**Given** user is viewing the list of potential animal facilities
**When** the user selects a facility
**And** the facility is capable of storing the animal
**Then** the user should be taken back to the main menu

**Given** user is viewing the list of potential animal facilities
**When** the user selects a facility
**And** the facility is incapable of storing the animal
**Then** the user should be presented with a message to select another facility
**And** the list of facilities should be shown again

**Comment by askingalot** [comment]
Replaced with more specific stories
