### ISSUE TITLE
User can build facility

### ISSUE THREAD

**Issue by stevebrownlee** [nashville-software-school/Trestlebridge-Farms#4]
**Given** a user has launched the program
**When** the user selects the option to create a facility
**Then** the user should be presented with a list of all possible facilities for use on the farm

**Given** user is viewing the list of facilities
**When** the user chooses which facility to buy
**Then** the user should be presented with a message confirming the creation of the facility
**And** the user should be presented with the main menu again

**Comment by askingalot** [comment]
Replaced with more specific stories
